CustomParam = ""

[Logger]
FileName = "logs/driver.log"
LogLevel = "INFO"

[Clients]
[Clients.Core]
Address = "124.221.189.137:57081"
UseTLS = false
CertFilePath = ""
ClientId = ""
Username = ""
Password = ""

[Service]
ID = "37471183"
Name = "MQTT协议驱动-37471183"
Activated = false
[Service.Server]
Address = "0.0.0.0:43696"
UseTLS = false
CertFile = ""
KeyFile = ""